version: "3.7"

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss-local
    restart: unless-stopped
    ports:
      - "192.168.1.12:8085:80"
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./freshrss-data:/var/www/FreshRSS/data
