version: '3.3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "192.168.1.12:8080:80"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./files:/srv
      - filebrowser_data:/database
      - filebrowser_config:/config

volumes:
  filebrowser_data:
  filebrowser_config:
