version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "192.168.1.12:8080:80"
    environment:
      - PUID=1000           
      - PGID=1000         
    volumes:
      - /home:/srv                                
      - ./filebrowser/database:/database             
      - ./filebrowser/config:/config             
    restart: unless-stopped
