version: "3.7"
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    ports:
      - "192.168.1.xx:5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=192.168.1.12
      - GENERIC_TIMEZONE=Europe/Istanbul
      - N8N_PORT=5678
    volumes:
      - ./n8n-data:/home/node/.n8n
