version: '3.3'

services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "192.168.1.12:9090:9090"
    volumes:
      - ./linkding-data:/etc/linkding/data
    environment:
      - LD_SUPERUSER_NAME=admin
      - LD_SUPERUSER_PASSWORD=admin123
    restart: unless-stopped
