version: '3.3'

services:
  olivetin:
    image: jamesread/olivetin
    container_name: olivetin
    restart: unless-stopped
    ports:
      - "192.168.1.12:1337:1337"
    volumes:
      - ./olivetin-config:/config
